### ISSUE TITLE
[benchmark-activemq] Could not find the main class: org.fusesource.jmsbenchmark.Benchmark

### ISSUE THREAD

**Issue by grg350** [chirino/jms-benchmark#2]
Hi Chirino,

I am trying to benchmark activemq and using ~/bin/benchmark-activemq
I got the following error when i run:

CLASSPATH=:target/classes
java -server -Xmx2G org.fusesource.jmsbenchmark.Benchmark --provider activemq --display-errors --url tcp://localhost:61616 /opt/jms-benchmark-master/reports/rgurung/activemq-5.8.0-openwire.json
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jmsbenchmark/Benchmark
Caused by: java.lang.ClassNotFoundException: org.fusesource.jmsbenchmark.Benchmark
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.fusesource.jmsbenchmark.Benchmark. Program will exit.
ls: cannot access *.json: No such file or directory

Am i missing anything?

**Comment by grg350** [comment]
Updating pom.xml per Jiri's suggestion fixed it.

**Comment by shankarramr** [comment]
Sorry which suggestion and where? I am getting same error.

**Comment by oisinom** [comment]
I am getting similar errors with this?
Any ideas on how to resolve it?
