### ISSUE TITLE
./bin/activemq fail to work. it shows errors.

### ISSUE THREAD

**Issue by ghosert** [chirino/jms-benchmark#3]
My machine is Ubunt 12.04, everything seems fine when running this command: 

./bin/activemq

Maven repository downloaded everything and activemq is started, and then it shows me like this:
# 
# Benchmarking activemq-5.8.0-openwire at: tcp://localhost:61616

scenario  : throughput: , mode: topic, persistent: true, message_size: 100000, tx_size: 10, selector_complexity: 0, destination_count: 1, consumers: 100, producers: 100 ...................
Worker did not shutdown quickly.. interrupting thread.
Worker did not shutdown quickly.. interrupting thread.
Worker did not shutdown quickly.. interrupting thread.
Worker did not shutdown quickly.. interrupting thread.

So, after that, I can get nothing except "Worker did not shutdown quickly.. interrupting thread.", this shows repetitively, and thread seems stuck.

**Comment by chirino** [comment]
Sorry, I've been modifying the benchmark recently to increase the number scenarios tested and the current mix tends to generate too much load.  

Try checking out the 1.0.x branch.  That version should be a bit more stable:
https://github.com/chirino/jms-benchmark/tree/1.0.x

**Comment by ghosert** [comment]
Sure, I'm going to try it, Thanks for your quick response.

**Comment by ghosert** [comment]
Hi there,

hmm I switched to 1.0.x, when running ./bin/benchmark-activemq, I got this new error:

[INFO] Checking for multiple versions of scala
[INFO] includes = [**/*.scala,**/*.java,]
[INFO] excludes = []
[INFO] /home/jiawzhang/company/jms-benchmark/jms-benchmark-activemq/src/main/scala:-1: info: compiling
[INFO] Compiling 1 source files to /home/jiawzhang/company/jms-benchmark/jms-benchmark-activemq/target/classes at 1363839939663
[ERROR] error: error while loading ActiveMQConnectionFactory, Missing dependency 'class org.springframework.beans.factory.BeanNameAware', required by /home/jiawzhang/.m2/repository/org/apache/activemq/activemq-all/5.8.0/activemq-all-5.8.0.jar(org/apache/activemq/spring/ActiveMQConnectionFactory.class)
[ERROR] /home/jiawzhang/company/jms-benchmark/jms-benchmark-activemq/src/main/scala/org/fusesource/jmsbenchmark/ActiveMQScenario.scala:32: error: org.apache.activemq.spring.ActiveMQConnectionFactory does not have a constructor
[INFO]     val rc = new ActiveMQConnectionFactory
[INFO]              ^
[ERROR] two errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jms-benchmark-project ............................. SUCCESS [0.972s]
[INFO] jms-benchmark ..................................... SUCCESS [10.917s]
[INFO] jms-benchmark-stomp ............................... SUCCESS [4.265s]
[INFO] jms-benchmark-activemq ............................ FAILURE [1.822s]
[INFO] jms-benchmark-hornetq ............................. SKIPPED
[INFO] jms-benchmark-qpid ................................ SKIPPED
[INFO] jms-benchmark-qpid-1.0 ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by ghosert** [comment]
And if everything is ok, will  "./bin/benchmark-activemq" produce a html based report like what you have on your site. ?

**Comment by chirino** [comment]
ok. I just pushed up some fixes.  Please run 'mvn clean' before you try again.  And yes, the report should get generated.

**Comment by ghosert** [comment]
So I git pull your changes and switch the branch to 1.0.x. And run "./bin/benchmark-activemq" Some of the test senarios are successful, others are  not ( I pasted the error log below). But finally, all the scenarios are completed and I got this:

# 

# Stored: /home/jiawzhang/company/jms-benchmark/reports/company-ws/activemq-5.8.0-openwire.json

# ls: cannot access *.json: No such file or directory

# Results stored under: /home/jiawzhang/company/jms-benchmark/jms-benchmark-activemq/reports/company-ws

There is json file in reports/company-ws folder and there is index.html in jms-benchmark-activemq/reports folder. Open this index.html, I saw the info regarding my machine but all the digrams should be on the page aren't there, just the circling "./resources/ajax-loader.gif" there instead.

Could you mind enlightening me how to resolve this issue ? and below is the exceptions I got for some scenarios. Is that the error below cause the digram missed?

scenario  : 20b_1a_1topic_0 java.lang.ArithmeticException: / by zero
        at org.fusesource.jmsbenchmark.ActiveMQScenario.factory(ActiveMQScenario.scala:45)
        at org.fusesource.jmsbenchmark.JMSClientScenario$JMSClient$$anon$1.run(JMSClientScenario.scala:78)
.java.lang.ArithmeticException: / by zero
        at org.fusesource.jmsbenchmark.ActiveMQScenario.factory(ActiveMQScenario.scala:45)
        at org.fusesource.jmsbenchmark.JMSClientScenario$JMSClient$$anon$1.run(JMSClientScenario.scala:78)
.java.lang.ArithmeticException: / by zero
        at org.fusesource.jmsbenchmark.ActiveMQScenario.factory(ActiveMQScenario.scala:45)
        at org.fusesource.jmsbenchmark.JMSClientScenario$JMSClient$$anon$1.run(JMSClientScenario.scala:78)
..java.lang.ArithmeticException: / by zero
        at org.fusesource.jmsbenchmark.ActiveMQScenario.factory(ActiveMQScenario.scala:45)
        at org.fusesource.jmsbenchmark.JMSClientScenario$JMSClient$$anon$1.run(JMSClientScenario.scala:78)
.java.lang.ArithmeticException: / by zero

**Comment by ghosert** [comment]
Hi there, any updates ? :+1:  we are evaluating different JMS candidates, your tool is the key. :+1:

**Comment by chirino** [comment]
Coolio.  What browser are you using?  Try firefox.

On Mon, Mar 25, 2013 at 3:46 AM, Jay Zhang notifications@github.com wrote:

> Hi chirino:
> 
> I take a look into the codes, and to avoid the 0 zero issue above, I
> changed codes in ActiveMQScenario.scala line 45 like this:
> - if (consumers != 0 && message_size != 0) { // jiawzhang add for fix
>   divided by 0 issue.
> - val prefech_size = prefetch_available_heap/(consumers*message_size)
> - if( prefech_size < 1000 ) {
> - rc.getPrefetchPolicy.setAll(prefech_size.toInt)
> - }
> - }
> 
> I checked consumers and message_size to make sure they are not zero. And
> then run _/bin/benchmark-activemq_, the issue has gone, but still, there
> are no digram showing on the report page. Instead, there are circling icons.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chirino/jms-benchmark/issues/3#issuecomment-15381012
> .

## 

**

_Hiram Chirino_

_Engineering | Red Hat, Inc._

_hchirino@redhat.com hchirino@redhat.com | fusesource.com | redhat.com_

*skype: hiramchirino | twitter: @hiramchirinohttp://twitter.com/hiramchirino
*

_blog: Hiram Chirino's Bit Mojo http://hiramchirino.com/blog/_

**Comment by ghosert** [comment]
im using ff it seems your generated json is not in the same location of
index.html
ÔÚ 2013-3-25 ÏÂÎç11:08£¬"Hiram Chirino" notifications@github.comÐ´µÀ£º

**Comment by ghosert** [comment]
I could get the diagram only, if I "cd jms-benchmark-activemq" first, and run "../bin/benchmark-activemq" and then the generated json will be put into "jms-benchmark-activemq/reports", then I got diagrams by opening index.html

I saw this is because ./jms-benchmark/bin/activemq-setup line 5 you are using `pwd`/reports/`hostname` for REPORTS_HOME, so I could only run ./bin/benchmark-activemq in jms-benchmark-activemq to make sure the json file is generated into the same reports folder with index.html

I think this is a bug, are u going to fix ?

And also Zero issue above I have to fix the line 45 of your ActiveMQScenario.scala to check consumers and message_size are both not 0.
